CREATE EXTERNAL TABLE IF NOT EXISTS silver_web_extracts (
    company_key STRING,
    domain STRING,
    crawl_ts STRING,
    page_url STRING,
    title STRING,
    meta_description STRING,
    about_snippet STRING,
    full_content STRING,
    content_length INT,
    word_count INT,
    social_links STRING,
    clients_mentions ARRAY<STRING>,
    testimonials ARRAY<STRING>,
    case_studies ARRAY<STRING>,
    solutions ARRAY<STRING>,
    tech_hints ARRAY<STRING>,
    programming_languages ARRAY<STRING>,
    frameworks ARRAY<STRING>,
    databases ARRAY<STRING>,
    cloud_providers ARRAY<STRING>,
    cms_platforms ARRAY<STRING>,
    analytics_tools ARRAY<STRING>,
    content_categories ARRAY<STRING>,
    topics ARRAY<STRING>,
    keywords ARRAY<STRING>,
    content_richness_score DECIMAL(3,2),
    readability_score DECIMAL(3,2),
    technical_depth_score DECIMAL(3,2),
    business_info_score DECIMAL(3,2),
    is_company_website BOOLEAN,
    page_type STRING,
    created_at STRING,
    updated_at STRING
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://thera-curated-805595753342-v3/silver/web_extracts/';
