-- =============================================================================
-- CTAS QUERIES FOR SILVER AND GOLD TABLES
-- =============================================================================
-- This script contains CTAS (CREATE TABLE AS SELECT) queries to populate
-- SILVER and GOLD tables with proper partitioning by dt

-- =============================================================================
-- SILVER LAYER CTAS QUERIES
-- =============================================================================

-- 1. Populate silver_companies
CREATE TABLE IF NOT EXISTS thera_silver.silver_companies AS
SELECT 
    company_key,
    domain,
    linkedin_url,
    company_name,
    legal_name,
    dba_name,
    country,
    state_province,
    city,
    postal_code,
    timezone,
    industry,
    sub_industry,
    industry_category,
    naics_code,
    sic_code,
    description,
    short_description,
    founded_year,
    founded_month,
    founded_date,
    employee_count,
    employee_range,
    revenue_range,
    size_bracket,
    total_funding,
    last_funding_date,
    last_funding_type,
    last_funding_amount,
    funding_stage,
    valuation,
    website_url,
    facebook_url,
    twitter_url,
    instagram_url,
    youtube_url,
    github_url,
    data_quality_score,
    source_priority,
    source_systems,
    confidence_score,
    duplicate_group_id,
    is_primary_record,
    duplicate_reason,
    survivorship_rules_applied,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_silver.silver_companies_temp
WHERE is_primary_record = true;

-- 2. Populate silver_apollo_companies
CREATE TABLE IF NOT EXISTS thera_silver.silver_apollo_companies AS
SELECT 
    apollo_id,
    apollo_url,
    company_key,
    domain,
    apollo_organization_id,
    name,
    legal_name,
    dba_name,
    website_url,
    country,
    state_province,
    city,
    postal_code,
    address_line1,
    address_line2,
    timezone,
    latitude,
    longitude,
    industry,
    sub_industry,
    industry_category,
    naics_code,
    sic_code,
    industry_tags,
    description,
    short_description,
    tagline,
    founded_year,
    founded_month,
    founded_date,
    employee_count,
    employee_range,
    revenue_range,
    annual_revenue,
    total_funding,
    last_funding_date,
    last_funding_type,
    last_funding_amount,
    funding_stage,
    valuation,
    linkedin_url,
    facebook_url,
    twitter_url,
    instagram_url,
    youtube_url,
    github_url,
    crunchbase_url,
    apollo_organization_type,
    apollo_organization_status,
    apollo_organization_size,
    apollo_organization_industry,
    apollo_organization_website,
    apollo_organization_phone,
    apollo_organization_email,
    technology_stack,
    programming_languages,
    frameworks,
    databases,
    cloud_providers,
    data_quality_score,
    completeness_score,
    accuracy_score,
    freshness_score,
    is_valid_domain,
    is_valid_email,
    is_valid_phone,
    is_valid_website,
    has_complete_address,
    has_industry_classification,
    source_system,
    source_record_id,
    raw_data_hash,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_silver.silver_apollo_companies_temp;

-- 3. Populate silver_apollo_contacts
CREATE TABLE IF NOT EXISTS thera_silver.silver_apollo_contacts AS
SELECT 
    apollo_id,
    apollo_url,
    contact_key,
    company_key,
    apollo_organization_id,
    first_name_masked,
    last_name_masked,
    full_name_masked,
    first_name_hash,
    last_name_hash,
    full_name_hash,
    title,
    department,
    seniority_level,
    job_function,
    job_title_normalized,
    email_masked,
    email_hash,
    phone_masked,
    phone_hash,
    linkedin_url,
    twitter_url,
    company_name,
    company_domain,
    company_industry,
    company_size_range,
    company_location,
    years_experience,
    education_level,
    education_institution,
    skills,
    certifications,
    languages,
    contact_status,
    contact_source,
    contact_quality_score,
    is_verified,
    is_senior_level,
    is_decision_maker,
    data_quality_score,
    completeness_score,
    accuracy_score,
    freshness_score,
    is_valid_email,
    is_valid_phone,
    is_valid_linkedin,
    has_complete_name,
    has_professional_info,
    has_company_association,
    source_system,
    source_record_id,
    raw_data_hash,
    pii_masking_applied,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_silver.silver_apollo_contacts_temp;

-- 4. Populate silver_domain_health
CREATE TABLE IF NOT EXISTS thera_silver.silver_domain_health AS
SELECT 
    domain,
    company_key,
    health_score,
    overall_grade,
    risk_level,
    is_https_enabled,
    ssl_grade,
    ssl_expiry_date,
    is_ssl_valid,
    page_load_time_ms,
    performance_grade,
    mobile_performance_score,
    desktop_performance_score,
    seo_score,
    seo_grade,
    has_meta_description,
    has_meta_keywords,
    has_structured_data,
    title_tag_length,
    meta_description_length,
    security_score,
    security_grade,
    has_security_headers,
    has_hsts_header,
    has_csp_header,
    has_xss_protection,
    is_malware_detected,
    is_phishing_detected,
    accessibility_score,
    accessibility_grade,
    has_alt_text,
    has_heading_structure,
    has_aria_labels,
    color_contrast_score,
    domain_age_days,
    domain_authority_score,
    backlink_count,
    referring_domains_count,
    spam_score,
    social_media_score,
    has_linkedin,
    has_facebook,
    has_twitter,
    has_instagram,
    has_youtube,
    has_github,
    content_quality_score,
    content_freshness_score,
    has_blog,
    has_news_section,
    has_about_page,
    has_contact_page,
    has_privacy_policy,
    has_terms_of_service,
    business_credibility_score,
    has_contact_info,
    has_physical_address,
    has_phone_number,
    has_email_address,
    has_team_page,
    has_careers_page,
    has_pricing_page,
    technology_score,
    uses_modern_framework,
    uses_cdn,
    uses_analytics,
    uses_heatmaps,
    uses_chat_widget,
    uses_live_chat,
    health_flags,
    critical_issues,
    warnings,
    recommendations,
    data_quality_score,
    completeness_score,
    accuracy_score,
    freshness_score,
    is_valid_domain,
    is_domain_resolvable,
    is_website_accessible,
    is_analysis_complete,
    source_system,
    analysis_job_id,
    analysis_timestamp,
    analysis_duration_seconds,
    raw_analysis_data,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_silver.silver_domain_health_temp;

-- 5. Populate silver_web_extracts
CREATE TABLE IF NOT EXISTS thera_silver.silver_web_extracts AS
SELECT 
    company_key,
    domain,
    crawl_ts,
    page_url,
    title,
    meta_description,
    meta_keywords,
    page_type,
    about_snippet,
    full_content,
    content_length,
    word_count,
    social_links,
    clients_mentions,
    testimonials,
    case_studies,
    tech_hints,
    programming_languages,
    frameworks,
    databases,
    cloud_providers,
    cms_platforms,
    analytics_tools,
    content_richness_score,
    readability_score,
    technical_depth_score,
    business_info_score,
    has_meta_description,
    has_meta_keywords,
    has_structured_data,
    has_heading_structure,
    has_internal_links,
    has_external_links,
    has_images,
    has_videos,
    company_size_hints,
    industry_hints,
    location_hints,
    funding_hints,
    team_hints,
    contact_info,
    navigation_items,
    footer_links,
    cta_buttons,
    forms_detected,
    content_categories,
    topics,
    keywords,
    data_quality_score,
    completeness_score,
    accuracy_score,
    freshness_score,
    is_valid_url,
    is_accessible,
    has_content,
    is_company_website,
    content_hash,
    source_system,
    firecrawl_job_id,
    raw_data_hash,
    extraction_method,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_silver.silver_web_extracts_temp;

-- =============================================================================
-- GOLD LAYER CTAS QUERIES
-- =============================================================================

-- 6. Populate gold_startup_profiles
CREATE TABLE IF NOT EXISTS thera_gold.gold_startup_profiles AS
SELECT 
    company_key,
    domain,
    company_name,
    legal_name,
    dba_name,
    linkedin_url,
    website_url,
    country,
    state_province,
    city,
    industry,
    sub_industry,
    industry_category,
    size_bracket,
    description,
    short_description,
    tagline,
    founded_year,
    founded_date,
    employee_count,
    employee_range,
    revenue_range,
    total_funding,
    last_funding_date,
    last_funding_type,
    last_funding_amount,
    funding_stage,
    valuation,
    domain_health_score,
    domain_grade,
    risk_level,
    health_flags,
    critical_issues,
    apollo_contact_count,
    apollo_has_verified_contact,
    apollo_seniority_mix,
    apollo_contact_quality_score,
    web_title,
    web_meta_description,
    web_about_snippet,
    web_content_categories,
    web_topics,
    web_keywords,
    social_media_presence,
    social_media_score,
    technology_stack,
    programming_languages,
    frameworks,
    databases,
    cloud_providers,
    cms_platforms,
    analytics_tools,
    technology_score,
    content_richness_score,
    content_quality_grade,
    readability_score,
    technical_depth_score,
    business_info_score,
    business_credibility_score,
    has_contact_info,
    has_physical_address,
    has_team_page,
    has_careers_page,
    has_pricing_page,
    has_privacy_policy,
    has_terms_of_service,
    clients_mentions,
    testimonials,
    case_studies,
    client_credibility_score,
    overall_data_quality_score,
    data_completeness_score,
    data_accuracy_score,
    data_freshness_score,
    confidence_level,
    profile_text,
    profile_text_hash,
    profile_summary,
    profile_tags,
    startup_stage,
    growth_indicators,
    innovation_indicators,
    market_presence_score,
    competitive_advantage_score,
    investment_readiness_score,
    investment_readiness_grade,
    funding_readiness_indicators,
    due_diligence_red_flags,
    market_size_estimate,
    target_market,
    competitive_landscape,
    market_opportunity_score,
    source_systems,
    last_updated_source,
    profile_generation_method,
    created_at,
    updated_at,
    last_verified_at,
    dt
FROM thera_gold.gold_startup_profiles_temp;

-- =============================================================================
-- CLEANUP TEMPORARY TABLES
-- =============================================================================

-- Drop temporary tables after successful population
DROP TABLE IF EXISTS thera_silver.silver_companies_temp;
DROP TABLE IF EXISTS thera_silver.silver_apollo_companies_temp;
DROP TABLE IF EXISTS thera_silver.silver_apollo_contacts_temp;
DROP TABLE IF EXISTS thera_silver.silver_domain_health_temp;
DROP TABLE IF EXISTS thera_silver.silver_web_extracts_temp;
DROP TABLE IF EXISTS thera_gold.gold_startup_profiles_temp;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

-- Verify table counts
SELECT 'silver_companies' as table_name, COUNT(*) as record_count FROM thera_silver.silver_companies
UNION ALL
SELECT 'silver_apollo_companies', COUNT(*) FROM thera_silver.silver_apollo_companies
UNION ALL
SELECT 'silver_apollo_contacts', COUNT(*) FROM thera_silver.silver_apollo_contacts
UNION ALL
SELECT 'silver_domain_health', COUNT(*) FROM thera_silver.silver_domain_health
UNION ALL
SELECT 'silver_web_extracts', COUNT(*) FROM thera_silver.silver_web_extracts
UNION ALL
SELECT 'gold_startup_profiles', COUNT(*) FROM thera_gold.gold_startup_profiles;

-- =============================================================================
-- NOTES FOR CONFIGURATION
-- =============================================================================
-- 1. Run these CTAS queries in order to populate the tables
-- 2. Monitor query performance and adjust partitioning if needed
-- 3. Consider adding indexes on frequently queried columns
-- 4. Add data validation checks after population
-- 5. Consider adding incremental updates for large datasets
-- 6. Monitor S3 storage costs and implement lifecycle policies
