CREATE TABLE IF NOT EXISTS gold_advanced_summaries (
    company_key STRING NOT NULL,
    domain STRING NOT NULL,
    company_name STRING NOT NULL,
    executive_summary STRING,
    executive_summary_hash STRING,
    executive_summary_confidence DECIMAL(3,2),
    key_insights ARRAY<STRING>,
    key_insights_hash STRING,
    business_model STRING,
    value_proposition STRING,
    target_customers ARRAY<STRING>,
    revenue_model STRING,
    technology_stack_analysis STRING,
    tech_stack_hash STRING,
    competitive_analysis STRING,
    competitive_analysis_hash STRING,
    risk_assessment STRING,
    risk_assessment_hash STRING,
    business_intelligence STRING,
    business_intelligence_hash STRING,
    investment_analysis STRING,
    investment_analysis_hash STRING,
    market_analysis STRING,
    market_analysis_hash STRING,
    growth_indicators ARRAY<STRING>,
    innovation_indicators ARRAY<STRING>,
    traction_indicators ARRAY<STRING>,
    scalability_indicators ARRAY<STRING>,
    summary_quality_score DECIMAL(3,2),
    data_completeness_score DECIMAL(3,2),
    confidence_level STRING,
    validation_status STRING,
    llm_model_used STRING,
    processing_cost_usd DECIMAL(10,6),
    processing_time_ms INT,
    tokens_used INT,
    batch_id STRING,
    content_hash STRING,
    last_content_update TIMESTAMP,
    summary_generation_method STRING,
    source_systems ARRAY<STRING>,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_verified_at TIMESTAMP
)
COMMENT 'Advanced LLM-powered summarization and business intelligence analysis'
STORED AS PARQUET
LOCATION 's3://thera-curated-805595753342-v3/gold/advanced_summaries/';
