AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AMS Computation Lambda Function for Challenge Scoring Metrics'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  CuratedBucket:
    Type: String
    Description: S3 bucket for curated data storage
    Default: thera-curated
  
  MetricsBucket:
    Type: String
    Description: S3 bucket for metrics storage
    Default: thera-metrics
  
  AthenaDatabase:
    Type: String
    Description: Athena database name
    Default: thera_analytics
  
  AthenaWorkgroup:
    Type: String
    Description: Athena workgroup name
    Default: primary
  
  DaysLookback:
    Type: Number
    Default: 1
    Description: Number of days to look back for data
    MinValue: 1
    MaxValue: 30

Resources:
  # IAM Role for Lambda
  AMSComputationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-ams-computation-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AMSComputationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${CuratedBucket}/*'
                  - !Sub 'arn:aws:s3:::${MetricsBucket}/*'
                  - !Sub 'arn:aws:s3:::${CuratedBucket}'
                  - !Sub 'arn:aws:s3:::${MetricsBucket}'
              
              # Athena permissions
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StopQueryExecution
                  - athena:GetWorkGroup
                Resource: '*'
              
              # CloudWatch permissions
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'

  # Lambda Function
  AMSComputationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-ams-computation'
      CodeUri: .
      Handler: lambda-ams-computation.lambda_handler
      Runtime: python3.12
      Timeout: 900  # 15 minutes
      MemorySize: 1024
      Environment:
        Variables:
          CURATED_BUCKET: !Ref CuratedBucket
          METRICS_BUCKET: !Ref MetricsBucket
          ATHENA_DATABASE: !Ref AthenaDatabase
          ATHENA_WORKGROUP: !Ref AthenaWorkgroup
          DAYS_LOOKBACK: !Ref DaysLookback
          AWS_REGION: !Ref AWS::Region
      Role: !GetAtt AMSComputationRole.Arn
      Events:
        # Daily trigger
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)  # Daily at 2 PM UTC
            Name: !Sub '${Environment}-ams-daily-trigger'
            Description: 'Daily trigger for AMS computation'
            Enabled: true
      Tags:
        Environment: !Ref Environment
        Service: thera-pipeline
        Component: ams-computation

  # CloudWatch Log Group
  AMSComputationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-ams-computation'
      RetentionInDays: 14

  # S3 Bucket for metrics (if not exists)
  MetricsBucketResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MetricsBucket
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: thera-pipeline
        - Key: Component
          Value: metrics-storage

  # Glue Table for AMS metrics (for querying)
  AMSMetricsGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaDatabase
      TableInput:
        Name: ams_metrics
        Description: 'AMS metrics table'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file
        StorageDescriptor:
          Columns:
            - Name: date
              Type: string
            - Name: total_challenges
              Type: int
            - Name: total_shortlists
              Type: int
            - Name: avg_ams_challenge
              Type: double
            - Name: avg_embedding_similarity
              Type: double
            - Name: avg_ml_score
              Type: double
            - Name: computed_at
              Type: string
          Location: !Sub 's3://${MetricsBucket}/ams/overall/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        PartitionKeys:
          - Name: date
            Type: string

  # Glue Table for challenge metrics
  ChallengeMetricsGlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaDatabase
      TableInput:
        Name: challenge_metrics
        Description: 'Challenge metrics table'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
          typeOfData: file
        StorageDescriptor:
          Columns:
            - Name: date
              Type: string
            - Name: challenge_id
              Type: string
            - Name: total_shortlists
              Type: int
            - Name: ams_challenge
              Type: double
            - Name: avg_embedding_similarity
              Type: double
            - Name: avg_ml_score
              Type: double
            - Name: top_score
              Type: double
            - Name: min_score
              Type: double
            - Name: score_std
              Type: double
            - Name: computed_at
              Type: string
          Location: !Sub 's3://${MetricsBucket}/ams/challenges/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        PartitionKeys:
          - Name: date
            Type: string

  # CloudWatch Alarms
  AMSComputationErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ams-computation-errors'
      AlarmDescription: 'AMS Computation Lambda errors'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AMSComputationFunction
      TreatMissingData: notBreaching

  AMSComputationDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ams-computation-duration'
      AlarmDescription: 'AMS Computation Lambda duration too high'
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 600000  # 10 minutes in milliseconds
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AMSComputationFunction
      TreatMissingData: notBreaching

  # Custom metrics for business logic
  AMSLowScoreAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ams-low-score'
      AlarmDescription: 'Average AMS score is low'
      MetricName: AverageAMS
      Namespace: TheraPipeline/AMS
      Statistic: Average
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 0.3
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching

  AMSNoDataAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${Environment}-ams-no-data'
      AlarmDescription: 'No shortlist data found for AMS computation'
      MetricName: TotalShortlists
      Namespace: TheraPipeline/AMS
      Statistic: Sum
      Period: 3600  # 1 hour
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching

Outputs:
  AMSComputationFunctionArn:
    Description: 'ARN of the AMS Computation Lambda function'
    Value: !GetAtt AMSComputationFunction.Arn
    Export:
      Name: !Sub '${Environment}-AMSComputationFunctionArn'
  
  AMSComputationRoleArn:
    Description: 'ARN of the AMS Computation IAM role'
    Value: !GetAtt AMSComputationRole.Arn
    Export:
      Name: !Sub '${Environment}-AMSComputationRoleArn'
  
  MetricsBucketName:
    Description: 'Name of the metrics S3 bucket'
    Value: !Ref MetricsBucketResource
    Export:
      Name: !Sub '${Environment}-MetricsBucketName'
  
  MetricsBucketArn:
    Description: 'ARN of the metrics S3 bucket'
    Value: !GetAtt MetricsBucketResource.Arn
    Export:
      Name: !Sub '${Environment}-MetricsBucketArn'